# Generated by Django 3.1.3 on 2020-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='rate',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
